# Production stack:
#   docker compose up --build
name: instanct

services:
  # mysql:
  #   image: mysql:8.0
  #   container_name: instanct_mysql
  #   restart: always
  #   env_file: env/prod/infra.env
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   healthcheck:
  #     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  rustfs:
    image: rustfs/rustfs:latest
    container_name: instanct_rustfs
    restart: always
    env_file: env/prod/infra.env
    command: --address :9000 --console-address :9001 /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - rustfs_data:/data



  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    image: instanct-api:prod
    container_name: instanct_api
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # depends_on:
    #   mysql:
    #     condition: service_healthy
    env_file: env/prod/api.env
    ports:
      - "5000:5000"

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        WEB_ENV_FILE: env/prod/web.env
    image: instanct-web:prod
    container_name: instanct_web
    restart: on-failure
    depends_on:
      - api
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file: env/prod/web.env
    ports:
      - "3000:3000"

  landing:
    build:
      context: .
      dockerfile: apps/landing/Dockerfile
      args:
        LANDING_ENV_FILE: env/prod/landing.env
    image: instanct-landing:prod
    container_name: instanct_landing
    restart: on-failure
    depends_on:
      - api
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file: env/prod/landing.env
    ports:
      - "3001:3001"

# volumes:
#   mysql_data:
volumes:
  rustfs_data:
