packages:
  - "apps/*"
  - "packages/*"

nodeLinker: hoisted

supportedArchitectures:
  os:
    - darwin
  cpu:
    - arm64
    - x64

overrides:
  react-native-worklets: "0.13.0"
  react: "19.3.0"
  react-dom: "19.3.0"

allowBuilds:
  bcrypt: true
  "@swc/core": true
  esbuild: true
  sharp: true
  unrs-resolver: true
  "@sentry/cli": true
  "@scarf/scarf": false
  core-js: false

minimumReleaseAgeExclude:
  - '@expo/*'
  - 'expo*'
  - 'babel-preset-expo*'

