packages:
  - "apps/*"
  - "packages/*"

nodeLinker: hoisted

overrides:
  react-native-worklets: "0.10.1"
  react: "19.2.3"
  react-dom: "19.2.3"

allowBuilds:
  bcrypt: true
  "@swc/core": true
  esbuild: true
  sharp: true
  unrs-resolver: true
