export enum EventType {
  SIGNIN = 'SIGNIN',
  SIGNUP = 'SIGNUP',
  SIGNOUT = 'SIGNOUT',

  CLIENT_SIGNIN = 'CLIENT_SIGNIN',
  CLIENT_SIGNUP = 'CLIENT_SIGNUP',

  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',
  USER_ACTIVATE = 'USER_ACTIVATE',
  USER_DEACTIVATE = 'USER_DEACTIVATE',
  USER_APPROVE = 'USER_APPROVE',
  USER_DISAPPROVE = 'USER_DISAPPROVE',

  USER_FOLLOW = 'USER_FOLLOW',
  USER_UNFOLLOW = 'USER_UNFOLLOW',

  USER_ADD_EXPERIENCE = 'USER_ADD_EXPERIENCE',
  USER_UPDATE_EXPERIENCE = 'USER_UPDATE_EXPERIENCE',
  USER_DELETE_EXPERIENCE = 'USER_DELETE_EXPERIENCE',

  USER_ADD_EDUCATION = 'USER_ADD_EDUCATION',
  USER_UPDATE_EDUCATION = 'USER_UPDATE_EDUCATION',
  USER_DELETE_EDUCATION = 'USER_DELETE_EDUCATION',

  ROLE_CREATE = 'ROLE_CREATE',
  ROLE_UPDATE = 'ROLE_UPDATE',
  ROLE_DELETE = 'ROLE_DELETE',
  ROLE_DUPLICATE = 'ROLE_DUPLICATE',

  DEVICE_INFO_CREATE = 'DEVICE_INFO_CREATE',
  DEVICE_INFO_DELETE = 'DEVICE_INFO_DELETE',

  BUG_CREATE = 'BUG_CREATE',
  BUG_DELETE = 'BUG_DELETE',

  FEEDBACK_CREATE = 'FEEDBACK_CREATE',
  FEEDBACK_DELETE = 'FEEDBACK_DELETE',

  REF_TYPE_CREATE = 'REF_TYPE_CREATE',
  REF_TYPE_UPDATE = 'REF_TYPE_UPDATE',
  REF_TYPE_DELETE = 'REF_TYPE_DELETE',

  REF_PARAM_CREATE = 'REF_PARAM_CREATE',
  REF_PARAM_UPDATE = 'REF_PARAM_UPDATE',
  REF_PARAM_DELETE = 'REF_PARAM_DELETE',

  SESSION_START = 'SESSION_START',
  SESSION_END = 'SESSION_END',

  REQUEST_CREATED = 'REQUEST_CREATED',
  REQUEST_ACCEPTED = 'REQUEST_ACCEPTED',
  REQUEST_REJECTED = 'REQUEST_REJECTED',

  BOOKMARK_CREATED = 'BOOKMARK_CREATED',
  BOOKMARK_DELETED = 'BOOKMARK_DELETED',
}
