export enum NotificationType {
  TEST = 'TEST',
  NEW_SIGNIN = 'NEW_SIGNIN',
  NEW_MESSAGE = 'NEW_MESSAGE',

  REQUEST_RECEIVED = 'REQUEST_RECEIVED',

  REQUEST_ACCEPTED = 'REQUEST_ACCEPTED',
  REQUEST_REJECTED = 'REQUEST_REJECTED',
}
