set $https_redirect 0;
if (-f /etc/nginx/https.enabled) {
    set $https_redirect 1;
}
if ($host = localhost) {
    set $https_redirect 0;
}
if ($host = sentry.instanct.com) {
    set $https_redirect 0;
}
if ($https_redirect = 1) {
    return 301 https://$host$request_uri;
}
